apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: storage.distort.io
  labels:
    {{- include "distort.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
