apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "distort.fullname" . }}-manager
  labels:
    {{- include "distort.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  replicas: {{ .Values.manager.replicaCount }}
  selector:
    matchLabels:
      {{- include "distort.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        {{- include "distort.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: manager
    spec:
      serviceAccountName: {{ include "distort.managerServiceAccountName" . }}
      containers:
        - name: manager
          image: {{ include "distort.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/distort-manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
      {{- include "distort.scheduling" (list . .Values.manager) | nindent 6 }}
