## Append samples of your project ##
resources:
- storage_v1alpha1_nvmedevice.yaml
- storage_v1alpha1_nvmedeviceclaim.yaml
- storage_v1alpha1_nvmepartition.yaml
- storage_v1alpha1_rdmastoragenode.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
