apiVersion: storage.distort.io/v1alpha1
kind: NVMePartition
metadata:
  labels:
    app.kubernetes.io/name: distort
    app.kubernetes.io/managed-by: kustomize
  name: nvmepartition-sample
spec:
  # Placement and claimRef are populated by the management controller.
  size: 1Gi
  targetBackend: spdk
  volumeManager: partition
  accessMode: SINGLE_NODE_WRITER
  filesystem: ext4
