/*
Copyright 2026, FORTH-ICS.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NVMePartitionState defines the lifecycle state of the partition.
type NVMePartitionState string

const (
	// NVMePartitionStatePending means the partition is waiting to be assigned to a node.
	NVMePartitionStatePending NVMePartitionState = "Pending"
	// NVMePartitionStateCreating means the agent is slicing the drive and exporting it.
	NVMePartitionStateCreating NVMePartitionState = "Creating"
	// NVMePartitionStateExported means the NVMe-oF target is active and ready.
	NVMePartitionStateExported NVMePartitionState = "Exported"
	// NVMePartitionStateFailed means the creation or export failed.
	NVMePartitionStateFailed NVMePartitionState = "Failed"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// NVMePartitionSpec defines the desired state of NVMePartition
type NVMePartitionSpec struct {
	// Size is the requested capacity for the volume.
	// +kubebuilder:validation:Required
	Size resource.Quantity `json:"size"`

	// NodeName is the node where this partition should be created.
	// Often left empty by the CSI provisioner and populated by the mutating scheduler.
	// +optional
	NodeName string `json:"nodeName,omitempty"`

	// ParentDeviceSerialNumber is the serial number of the NVMeDevice this partition is allocated from.
	// Populated by the mutating scheduler (Mgmt Controller).
	// +optional
	ParentDeviceSerialNumber string `json:"parentDeviceSerialNumber,omitempty"`

	// AccessMode indicates the PVC access mode (e.g., ReadWriteOnce, ReadOnlyMany).
	// +optional
	AccessMode string `json:"accessMode,omitempty"`

	// TargetBackend specifies the export technology (e.g., "spdk", "kernel", or "bxi").
	// +kubebuilder:validation:Enum=spdk;kernel;bxi
	// +kubebuilder:default=spdk
	// +optional
	TargetBackend string `json:"targetBackend,omitempty"`

	// VolumeManager specifies the volume manager (e.g., "partition" or "lvm").
	// +kubebuilder:validation:Enum=partition;lvm
	// +kubebuilder:default=partition
	// +optional
	VolumeManager string `json:"volumeManager,omitempty"`

	// TargetOptions provides backend-specific customization flags (e.g., spdk core masks).
	// +optional
	TargetOptions map[string]string `json:"targetOptions,omitempty"`
}

// NVMePartitionStatus defines the observed state of NVMePartition.
type NVMePartitionStatus struct {
	// State is the current status of the partition creation/export.
	// +kubebuilder:validation:Enum=Pending;Creating;Exported;Failed
	// +kubebuilder:default=Pending
	State NVMePartitionState `json:"state,omitempty"`

	// NQN is the NVMe Qualified Name generated by the agent upon successful export.
	// +optional
	NQN string `json:"nqn,omitempty"`

	// PortalIP is the RDMA IP address for the CSI node side to connect to.
	// +optional
	PortalIP string `json:"portalIP,omitempty"`

	// PortalPort is the RDMA port (default: 4420).
	// +optional
	PortalPort int `json:"portalPort,omitempty"`

	// Conditions represent the current state of the NVMePartition resource.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Size",type="string",JSONPath=".spec.size",description="Partition Size"
// +kubebuilder:printcolumn:name="Node",type="string",JSONPath=".spec.nodeName",description="Assigned Node"
// +kubebuilder:printcolumn:name="State",type="string",JSONPath=".status.state",description="Current State"
// +kubebuilder:printcolumn:name="NQN",type="string",JSONPath=".status.nqn",description="NVMe-oF NQN"
// +kubebuilder:printcolumn:name="Portal",type="string",JSONPath=".status.portalIP",description="Portal IP"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// NVMePartition is the Schema for the nvmepartitions API
type NVMePartition struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of NVMePartition
	// +required
	Spec NVMePartitionSpec `json:"spec"`

	// status defines the observed state of NVMePartition
	// +optional
	Status NVMePartitionStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// NVMePartitionList contains a list of NVMePartition
type NVMePartitionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []NVMePartition `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NVMePartition{}, &NVMePartitionList{})
}
