baseURL = 'https://distort-csi.dev/'
languageCode = 'en-us'
title = 'DISTORT Documentation'
theme = []
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "dracula"

[[menu.main]]
  name = "Architecture"
  url = "/architecture/"
  weight = 20

[[menu.main]]
  name = "Using"
  url = "/using/"
  weight = 25

[[menu.main]]
  name = "Contributing"
  url = "/contributing/"
  weight = 30
